# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: force_control.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='force_control.proto',
  package='gemini.forcecontrol',
  syntax='proto3',
  serialized_options=b'\n\026io.gemini.forcecontrolB\014ForceControlP\001\242\002\003HLW',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x66orce_control.proto\x12\x13gemini.forcecontrol\"T\n\x10GeneralizedForce\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\t\n\x01k\x18\x04 \x01(\x02\x12\t\n\x01m\x18\x05 \x01(\x02\x12\t\n\x01n\x18\x06 \x01(\x02\"a\n\x0c\x46orceRequest\x12\x10\n\x08vesselId\x18\x01 \x01(\t\x12?\n\x10generalizedForce\x18\x02 \x01(\x0b\x32%.gemini.forcecontrol.GeneralizedForce\" \n\rForceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x65\n\x0c\x46orceControl\x12U\n\nApplyForce\x12!.gemini.forcecontrol.ForceRequest\x1a\".gemini.forcecontrol.ForceResponse\"\x00\x42.\n\x16io.gemini.forcecontrolB\x0c\x46orceControlP\x01\xa2\x02\x03HLWb\x06proto3'
)




_GENERALIZEDFORCE = _descriptor.Descriptor(
  name='GeneralizedForce',
  full_name='gemini.forcecontrol.GeneralizedForce',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='gemini.forcecontrol.GeneralizedForce.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='gemini.forcecontrol.GeneralizedForce.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z', full_name='gemini.forcecontrol.GeneralizedForce.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='k', full_name='gemini.forcecontrol.GeneralizedForce.k', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='m', full_name='gemini.forcecontrol.GeneralizedForce.m', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='n', full_name='gemini.forcecontrol.GeneralizedForce.n', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=128,
)


_FORCEREQUEST = _descriptor.Descriptor(
  name='ForceRequest',
  full_name='gemini.forcecontrol.ForceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vesselId', full_name='gemini.forcecontrol.ForceRequest.vesselId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='generalizedForce', full_name='gemini.forcecontrol.ForceRequest.generalizedForce', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=227,
)


_FORCERESPONSE = _descriptor.Descriptor(
  name='ForceResponse',
  full_name='gemini.forcecontrol.ForceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='gemini.forcecontrol.ForceResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=229,
  serialized_end=261,
)

_FORCEREQUEST.fields_by_name['generalizedForce'].message_type = _GENERALIZEDFORCE
DESCRIPTOR.message_types_by_name['GeneralizedForce'] = _GENERALIZEDFORCE
DESCRIPTOR.message_types_by_name['ForceRequest'] = _FORCEREQUEST
DESCRIPTOR.message_types_by_name['ForceResponse'] = _FORCERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GeneralizedForce = _reflection.GeneratedProtocolMessageType('GeneralizedForce', (_message.Message,), {
  'DESCRIPTOR' : _GENERALIZEDFORCE,
  '__module__' : 'force_control_pb2'
  # @@protoc_insertion_point(class_scope:gemini.forcecontrol.GeneralizedForce)
  })
_sym_db.RegisterMessage(GeneralizedForce)

ForceRequest = _reflection.GeneratedProtocolMessageType('ForceRequest', (_message.Message,), {
  'DESCRIPTOR' : _FORCEREQUEST,
  '__module__' : 'force_control_pb2'
  # @@protoc_insertion_point(class_scope:gemini.forcecontrol.ForceRequest)
  })
_sym_db.RegisterMessage(ForceRequest)

ForceResponse = _reflection.GeneratedProtocolMessageType('ForceResponse', (_message.Message,), {
  'DESCRIPTOR' : _FORCERESPONSE,
  '__module__' : 'force_control_pb2'
  # @@protoc_insertion_point(class_scope:gemini.forcecontrol.ForceResponse)
  })
_sym_db.RegisterMessage(ForceResponse)


DESCRIPTOR._options = None

_FORCECONTROL = _descriptor.ServiceDescriptor(
  name='ForceControl',
  full_name='gemini.forcecontrol.ForceControl',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=263,
  serialized_end=364,
  methods=[
  _descriptor.MethodDescriptor(
    name='ApplyForce',
    full_name='gemini.forcecontrol.ForceControl.ApplyForce',
    index=0,
    containing_service=None,
    input_type=_FORCEREQUEST,
    output_type=_FORCERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FORCECONTROL)

DESCRIPTOR.services_by_name['ForceControl'] = _FORCECONTROL

# @@protoc_insertion_point(module_scope)
